namespace DirtAndDiamonds.Simulation.Baseball;

/// <summary>
/// Analytic representation of the outer chain (micro doc §3–§4): the per-event
/// 25×25 advancement matrices A_e mandated by baseball_engine.md §2, the
/// composed per-matchup transition matrix T = Σ p_e·A_e, and the absorbing-
/// chain analysis (fundamental matrix → run expectancy) built on it.
///
/// Every matrix row is generated by executing the SAME deterministic
/// advancement cores in <see cref="BaseOutAdvancement"/> that the runtime hot
/// path calls — enumerating the one discretionary branch of Single/Double with
/// the shared knob weights — so the analytic and runtime representations are
/// equivalent by construction, not by parallel maintenance.
///
/// This is offline/load-time/validation code (§3.3): it allocates freely and
/// must never be called from a per-PA or per-pitch loop. The runtime applies
/// the advancement functions directly and never materializes a matrix.
/// </summary>
public static class BaseOutMatrices
{
    public const int StateCount = BaseOutAdvancement.StateCount;
    private const int Transients = BaseOutAdvancement.TransientStateCount;

    /// <summary>
    /// Builds the row-stochastic A_e for one event into <paramref name="matrix"/>
    /// (row-major 25×25) and the expected runs scored on each transition into
    /// <paramref name="expectedRuns"/> (per source state). The absorbing state
    /// self-loops with no reward.
    /// </summary>
    public static void BuildEventMatrix(PaOutcome outcome, double[] matrix, double[] expectedRuns)
    {
        if (matrix.Length != StateCount * StateCount || expectedRuns.Length != StateCount)
        {
            throw new ArgumentException("BuildEventMatrix requires a 25×25 matrix and a 25-wide reward vector.");
        }
        Array.Clear(matrix);
        Array.Clear(expectedRuns);
        matrix[BaseOutAdvancement.AbsorbingState * StateCount + BaseOutAdvancement.AbsorbingState] = 1.0;

        for (int state = 0; state < Transients; state++)
        {
            int bases = BaseOutAdvancement.BasesOfState(state);
            int outs = BaseOutAdvancement.OutsOfState(state);

            switch (outcome)
            {
                case PaOutcome.Out:
                case PaOutcome.Strikeout:
                {
                    int successor = BaseOutAdvancement.ToState(bases, outs + 1);
                    matrix[state * StateCount + successor] = 1.0;
                    break;
                }
                case PaOutcome.Walk:
                {
                    int next = bases;
                    int runs = BaseOutAdvancement.AdvanceWalk(ref next);
                    matrix[state * StateCount + BaseOutAdvancement.ToState(next, outs)] = 1.0;
                    expectedRuns[state] = runs;
                    break;
                }
                case PaOutcome.Single:
                {
                    AddBranch(matrix, expectedRuns, state, outs, bases,
                        hasBranch: (bases & 0b010) != 0, branchProbability: BaseOutAdvancement.SingleScoresFrom2nd,
                        advance: static (ref int b, bool scores) => BaseOutAdvancement.AdvanceSingle(ref b, scores));
                    break;
                }
                case PaOutcome.Double:
                {
                    AddBranch(matrix, expectedRuns, state, outs, bases,
                        hasBranch: (bases & 0b001) != 0, branchProbability: BaseOutAdvancement.DoubleScoresFrom1st,
                        advance: static (ref int b, bool scores) => BaseOutAdvancement.AdvanceDouble(ref b, scores));
                    break;
                }
                case PaOutcome.Triple:
                {
                    int next = bases;
                    int runs = BaseOutAdvancement.AdvanceTriple(ref next);
                    matrix[state * StateCount + BaseOutAdvancement.ToState(next, outs)] = 1.0;
                    expectedRuns[state] = runs;
                    break;
                }
                default: // HomeRun
                {
                    int next = bases;
                    int runs = BaseOutAdvancement.AdvanceHomeRun(ref next);
                    matrix[state * StateCount + BaseOutAdvancement.ToState(next, outs)] = 1.0;
                    expectedRuns[state] = runs;
                    break;
                }
            }
        }
    }

    private delegate int BranchedAdvance(ref int bases, bool discretionaryScores);

    /// <summary>Enumerates the discretionary branch of Single/Double with the knob weight.</summary>
    private static void AddBranch(
        double[] matrix, double[] expectedRuns, int state, int outs, int bases,
        bool hasBranch, double branchProbability, BranchedAdvance advance)
    {
        if (!hasBranch)
        {
            int next = bases;
            int runs = advance(ref next, false);
            matrix[state * StateCount + BaseOutAdvancement.ToState(next, outs)] = 1.0;
            expectedRuns[state] = runs;
            return;
        }

        int scoringBases = bases;
        int scoringRuns = advance(ref scoringBases, true);
        int holdingBases = bases;
        int holdingRuns = advance(ref holdingBases, false);

        matrix[state * StateCount + BaseOutAdvancement.ToState(scoringBases, outs)] += branchProbability;
        matrix[state * StateCount + BaseOutAdvancement.ToState(holdingBases, outs)] += 1.0 - branchProbability;
        expectedRuns[state] = branchProbability * scoringRuns + (1.0 - branchProbability) * holdingRuns;
    }

    /// <summary>
    /// Composes the one-PA transition matrix T(matchup) = Σ p_e·A_e (§3.2) and
    /// the per-state expected immediate runs r(s) = Σ p_e·runs_e(s) for a
    /// 7-way outcome distribution (typically AtBatResolver.ComputeProbabilities
    /// output).
    /// </summary>
    public static void ComposeTransition(
        ReadOnlySpan<double> outcomeProbabilities, double[] transition, double[] expectedRuns)
    {
        if (outcomeProbabilities.Length < AtBatResolver.OutcomeCount)
        {
            throw new ArgumentException("Need all 7 outcome probabilities.");
        }
        Array.Clear(transition);
        Array.Clear(expectedRuns);

        var eventMatrix = new double[StateCount * StateCount];
        var eventRuns = new double[StateCount];
        for (int e = 0; e < AtBatResolver.OutcomeCount; e++)
        {
            BuildEventMatrix((PaOutcome)e, eventMatrix, eventRuns);
            double p = outcomeProbabilities[e];
            for (int i = 0; i < transition.Length; i++)
            {
                transition[i] += p * eventMatrix[i];
            }
            for (int s = 0; s < StateCount; s++)
            {
                expectedRuns[s] += p * eventRuns[s];
            }
        }
    }

    /// <summary>
    /// §4: run expectancy for the 24 transient base-out states under a
    /// matchup's outcome distribution — RE(s) solves (I − Q)·RE = r, i.e.
    /// RE = N·r with N the fundamental matrix, by Gaussian elimination with
    /// partial pivoting. For a league-average matchup RE[state 0] reproduces
    /// the familiar RE24 anchor (~0.5 runs from 0-out bases-empty).
    /// </summary>
    public static double[] RunExpectancy(ReadOnlySpan<double> outcomeProbabilities)
    {
        var transition = new double[StateCount * StateCount];
        var rewards = new double[StateCount];
        ComposeTransition(outcomeProbabilities, transition, rewards);

        // Build (I − Q) over the transient block and solve against r.
        var a = new double[Transients * Transients];
        var x = new double[Transients];
        for (int i = 0; i < Transients; i++)
        {
            for (int j = 0; j < Transients; j++)
            {
                a[i * Transients + j] = (i == j ? 1.0 : 0.0) - transition[i * StateCount + j];
            }
            x[i] = rewards[i];
        }

        for (int col = 0; col < Transients; col++)
        {
            int pivot = col;
            for (int row = col + 1; row < Transients; row++)
            {
                if (Math.Abs(a[row * Transients + col]) > Math.Abs(a[pivot * Transients + col]))
                {
                    pivot = row;
                }
            }
            if (pivot != col)
            {
                for (int j = 0; j < Transients; j++)
                {
                    (a[col * Transients + j], a[pivot * Transients + j]) =
                        (a[pivot * Transients + j], a[col * Transients + j]);
                }
                (x[col], x[pivot]) = (x[pivot], x[col]);
            }

            double diag = a[col * Transients + col];
            for (int row = col + 1; row < Transients; row++)
            {
                double factor = a[row * Transients + col] / diag;
                if (factor == 0.0)
                {
                    continue;
                }
                for (int j = col; j < Transients; j++)
                {
                    a[row * Transients + j] -= factor * a[col * Transients + j];
                }
                x[row] -= factor * x[col];
            }
        }
        for (int row = Transients - 1; row >= 0; row--)
        {
            double sum = x[row];
            for (int j = row + 1; j < Transients; j++)
            {
                sum -= a[row * Transients + j] * x[j];
            }
            x[row] = sum / a[row * Transients + row];
        }
        return x;
    }
}
